# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'weibo-swift' do
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'Popover'
pod 'SnapKit', '~> 4.0.0'

end
